In [4]:
import pandas as pd
import numpy as np

## pandas.cut

In [5]:
pd.cut(np.array([.2, 1.4, 2.5, 6.2, 9.7, 2.1]), 3, retbins=True)

([(0.191, 3.367], (0.191, 3.367], (0.191, 3.367], (3.367, 6.533], (6.533, 9.7], (0.191, 3.367]]
 Categories (3, object): [(0.191, 3.367] < (3.367, 6.533] < (6.533, 9.7]],
 array([ 0.1905    ,  3.36666667,  6.53333333,  9.7       ]))

In [6]:
pd.cut(np.array([.2, 1.4, 2.5, 6.2, 9.7, 2.1]), 3,
      labels=["good","medium","bad"])

[good, good, good, medium, bad, good]
Categories (3, object): [good < medium < bad]

In [7]:
pd.cut(np.ones(5), 4, labels=False)

array([1, 1, 1, 1, 1])

## pandas.qcut

In [8]:
pd.qcut(range(5), 4)

[[0, 1], [0, 1], (1, 2], (2, 3], (3, 4]]
Categories (4, object): [[0, 1] < (1, 2] < (2, 3] < (3, 4]]

In [9]:
pd.qcut(range(5), 3, labels=["good","medium","bad"])

[good, good, medium, bad, bad]
Categories (3, object): [good < medium < bad]

In [10]:
pd.qcut(range(5), 4, labels=False)

array([0, 0, 1, 2, 3])

## SQL connection

In [2]:
import pyodbc
cnxn = pyodbc.connect('DRIVER={SQL Server};SERVER=qgivdatawarehouse.database.windows.net;DATABASE=analytics;UID=s3r8dm1n;PWD=S1ph3r!!')
cursor = cnxn.cursor()

In [4]:
cursor.execute('select top 10 * from analytic_base')
rows = cursor.fetchall()
for r in rows:
    print r

('""', '""', datetime.datetime(2015, 3, 21, 4, 0, 1), 5819147, 136, 251969, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), 0, None, 0, Decimal('0.0000'))
('"8398"', '"900413711"', datetime.datetime(2015, 3, 21, 4, 0, 1), 5819148, 867, 856, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), 0, None, 0, Decimal('0.0000'))
('"8398"', '""', datetime.datetime(2015, 3, 21, 4, 0, 1), 5819149, 31796, 103500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), 0, None, 0, Decimal('0.0000'))
('"8398"', '"742244826"', datetime.datetime(2015, 3, 21, 4, 0, 1), 5819150, 880, 869, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [8]:
fout=open("/Users/jerem/Downloads/trans_agg.csv","a")

# first file:
fname_base = '/Users/jerem/Downloads/transactions-'

for line in open(fname_base+"1000-50000.csv"):
    fout.write(line)

fname_ranges = [10000,30000,60000,110000,160000,210000,260000,310000,360000,410000,460000,510000,560000,610000,660000,710000,760000,810000,860000,910000,960000,1010000,1060000,1110000,1160000,1210000,1260000,1310000,1360000,1410000,1460000,1510000,1560000,1610000,1660000,1710000,1760000]
    
# now the rest:    
for num in fname_ranges:
    fname = fname_base+str(num)+"-50000.csv"
    print "opening "+fname+"..."
    f = open(fname)
    f.next() # skip the header
    for line in f:
         fout.write(line)
    f.close() # not really needed
    print "...closed "+fname
fout.close()

opening /Users/jerem/Downloads/transactions-10000-50000.csv...
...closed /Users/jerem/Downloads/transactions-10000-50000.csv
opening /Users/jerem/Downloads/transactions-30000-50000.csv...
...closed /Users/jerem/Downloads/transactions-30000-50000.csv
opening /Users/jerem/Downloads/transactions-60000-50000.csv...
...closed /Users/jerem/Downloads/transactions-60000-50000.csv
opening /Users/jerem/Downloads/transactions-110000-50000.csv...
...closed /Users/jerem/Downloads/transactions-110000-50000.csv
opening /Users/jerem/Downloads/transactions-160000-50000.csv...
...closed /Users/jerem/Downloads/transactions-160000-50000.csv
opening /Users/jerem/Downloads/transactions-210000-50000.csv...
...closed /Users/jerem/Downloads/transactions-210000-50000.csv
opening /Users/jerem/Downloads/transactions-260000-50000.csv...
...closed /Users/jerem/Downloads/transactions-260000-50000.csv
opening /Users/jerem/Downloads/transactions-310000-50000.csv...
...closed /Users/jerem/Downloads/transactions-310000-